controllers:
    resource: ../src/Controller/
    type: attribute

# kernel:
#     resource: ../src/Kernel.php
#     type: attribute

# create_employe:
#     path: /ajouter-un-employe
#     controller: App\Controller\EmployeController::createEmploye